name: Java CI with Allure Report

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually run the workflow from the GitHub UI

# Sets permissions for the deployment step
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Run the tests. This may fail, but we want to continue anyway.
      - name: Run tests with Maven
        run: mvn test
        continue-on-error: true

      # Step 4: Generate the Allure Report.
      - name: Generate Allure Report
        if: always()
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          ./allure-2.27.0/bin/allure generate allure-results -o allure-report --clean

      # Step 5: Configure GitHub Pages (NEW)
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      # Step 6: Upload the report to GitHub Pages (NEW)
      - name: Upload to GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report' # Upload the entire generated report folder

      # Step 7: Deploy to GitHub Pages (NEW)
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4
